# Generated by Django 4.2.29 on 2026-03-22 13:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_orderenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hub_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='hub_status',
            field=models.CharField(choices=[('pending_vendor_shipment', 'Pending — Vendor to Ship to Hub'), ('in_transit_to_hub', 'In Transit to Hub'), ('received_at_hub', 'Received at Hub'), ('packaged_for_customer', 'Packaged for Customer')], default='pending_vendor_shipment', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='package_scan_id',
            field=models.CharField(blank=True, help_text='Vendor-generated package ID scanned at the hub', max_length=50),
        ),
        migrations.CreateModel(
            name='MasterOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(max_length=100, unique=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('runner_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('awaiting_arrivals', 'Awaiting Arrivals at Hub'), ('ready_for_packaging', 'Ready for Final Packaging'), ('packaged', 'Packaged for Customer'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered to Customer'), ('confirmed', 'Buyer Confirmed'), ('cancelled', 'Cancelled')], default='awaiting_payment', max_length=25)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('hub_bin', models.CharField(blank=True, help_text='Physical bin/bag label at hub e.g. BIN-042', max_length=20)),
                ('packaged_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_orders', to=settings.AUTH_USER_MODEL)),
                ('delivery_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.campuszone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='master_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.masterorder'),
        ),
    ]
